flowchart TD



subgraph Operations ["Operations"]
    Oinc["++"]
    Oplus["+"]
    Ominus["−"]
    Omul["×"]
    Odiv["÷"]
    Opow["^"]
    Oeudiv["#/⟡"]
    Omod["⟡"]
    Olog["log(n)"]
    Oroot["^(1/n)"]
    
    subgraph Inputs ["Value Expression"]
        Ineg["0-n"]
        Ifrac["a/b"]
        Iroot["√"]
    
        subgraph Constants ["Constants"]
            Iim["i"]
            Ireal["π, e"]
            Idigits["0-9"]
        end
    end

    Oinc -->|Iterate| Oplus

    Oplus -->|Invert| Ominus
    Oplus -->|Iterate| Omul

    Omul -->|Decompose| Oeudiv
    Omul -->|Iterate| Opow
    
    Oeudiv -->|Generalize| Odiv
    Oeudiv -->|Remainder| Omod

    Opow -->|Invert| Oroot
    Opow -->|Invert| Olog
end

subgraph Expressable ["Expressable Values"]
    NN["ℕ (1)"]
    NZ["ℤ (-1)"]
    NQ["ℚ (1/2)"]
    NA["Algebraic (√2)"]
    NR["ℝ (π)"]
    NC["ℂ (√-1)"]
end

    NN --> NZ --> NQ --> NA --> NR --> NC
    
    Idigits --> NN
    
    Ineg --> NZ
    Ominus --> Ineg
    Odiv --> Ifrac
    Oroot --> Iroot
    
    Ifrac --> NQ
    
    Iroot --> NA
    Ireal --> NR

    Iim --> NC