%% Truth 4: Keep

%% ⋕
%% Design guidelines:
%% 1. All operators can be constructed from atomic primitives
%% 2. Operators can be unary (takes previous operator result) or binary (takes previous operator result and second operand)
%% 3. User enters initial seed value, operators, and binary operands. A combDOM_nation operator and second operand are a "operation slot"
%% 4. Values for seeds and binary operands can be digits 0-9
%% 
%% Theoretical progression path:
%% - Every subgraph defines its own calculator, which starts with its own settings, primitives, and visualizer locked in place (at first).
%% - Every calculator is equipped with the settings required to reason about that family of operators and intuitively understand the results.
%% - The player starts with the increment operator only, and must construct other operators to earn the right to think that way.
%% - All of the main arithmetic functions can be inverted. Sometimes inverses imply the existence of new numbers.
%% - Sometimes, using operators on these new types of numbers can have interesting outcomes
%% - Finding an interesting outcome in a new area unlocks a new calculator with that new outcome as an installed defined operator key
%% - New unlocks from within a family are added to that calculator directly - not yet freely movable
%% - Once all of an operator's child nodes are in play, that operator is free to swap and add to other calculators
%% - Multiple pathways to the same calculator might be possible, not sure yet
%% - Multiple pathways to the same key might be possible, not sure yet

flowchart TD

    subgraph Linear ["ℕ,ℤ"]
        MAT_inc
        MAT_plus
        MAT_mul
        GRO_pow

        MAT_dec
        MAT_minus
        MAT_eudiv
        MAT_eulog

        %% Lfloor
        %% Lceil
    end
    subgraph Ratios ["ℚ"]
        RAT_ratio

        RAT_mod

        RAT_recip
        RAT_div
        RAT_per

        subgraph Advanced
        MUS_whole
        MUS_semit
        MUS_inter
        RAT_cdiv
        end
    end

    subgraph Growth ["𝔸‾,ℂ"]

        GRO_sqrt
        GRO_dislog
        GRO_radical
        GRO_log   
        
        GRO_clog
        GRO_resid        
    end

    subgraph Boolean_Ops ["𝕋/𝔽"]

        BOO_notp
        BOO_ifelse
        BOO_and
        BOO_or

        subgraph Comparisons ["≤"]
        BOO_sign
        BOO_notgt
        BOO_less
        BOO_eq
        BOO_divis
        BOO_max
        BOO_minim
        end
    end

    subgraph Rotation_Ops ["× 𝕀"]

        ROT_twentyfourth
        ROT_rotate
        ROT_quarter
        ROT_half

        ROT_conj

        ROT_impart
        ROT_repart
        ROT_norm
        ROT_modulus
        ROT_c_tuple
        ROT_theta
    end     

    %% subgraph P_Theory ["Returns ℙ (2)"]
    %%     Pnthprime
    %%     Pindexofp

    %%     Padic
    %%     Pprime_expansion

    %%     Pomega        
    %%     Ptotient
    %%     Pdivisor_sum
        
    %%     Pgcd
    %%     Plcm
    %% end

%% Arithmatic
    %% Visualizer: cartesian plane (numberline when dealing with reals, then plane for complex numbers)
    
    MAT_inc[["[ n ++ ]"]]
    %% Primitive
    %% Expanded form `[ 4 ++ ]` -> `[ 4 ℕ{..3 4◌⃕5..} ]`
    %% Completes ℕ on its own
    MAT_inc ==>|Invert| MAT_dec["[ n -- ]"]
    %% Expanded form `[ 4 –– ]` -> `[ 4 ℤ{..3◌⃔4 5..} ]`
    %% Expanded form `[ 4 –– ]` -> `[ 4 ++⮌ ]`
    %% Completes ℤ with ++
    MAT_inc ==>|Iterate| MAT_plus["a [ \+b ]"]
    %% Expanded form `[ 4 + 3 ]` -> `[ 4 ++ ++ ++ ]`  
    MAT_plus ==>|Invert| MAT_minus["a [ − b ]"]
    %% Expanded form `[ 4 - 3 ]` -> `[ 4 +⮌ 3 ]`
    MAT_dec ==>|Iterate| MAT_minus["a [ − b ]"]
    %% Expanded form `[ 4 - 3 ]` -> `[ 4 –– –– –– ]`
    %% RAT_mod ==> Lfloor["⌊n⌋"]
    %% %% Expanded form `[ ⌊(4/3)⌋ ]` -> `[ (4/3) - ((4/3) ◇ 1) ]`
    %% Lfloor ==> Lceil["⌈n⌉"]
    %% %% Expanded form `[ ⌈(4/3)⌉ ]` -> `[ (4/3) + (1 - ((4/3) ◇ 1)) ]`
    
    MAT_plus ==>|Iterate| MAT_mul["a [ × b ]"]
    %% Expanded form `[ 4 × 3 ]` -> `[ 4 +4 +4 ]`
    %% ROT_impart ==> ROT_modulus
    %% ROT_repart ==> ROT_modulus
    %% ROT_rotate ==>|Iterate| ROT_half["n±"]
    
    MAT_mul ==>|Invert| MAT_eudiv["a ⫽ b"]
    MAT_minus ==>|Iterate| MAT_eudiv
    %% Expanded form `[ 4 ⫽ 3 ]` -> `Σ[ ¬(4 – (3 × ℕ)) ]`

    MAT_mul ==>|Iterate| GRO_pow["a [ ^ b ]"]
    %% Expanded form `[ 4 ^ 3 ]` -> `[ 4 ×4 ×4 ]`

    MAT_eudiv ==>|Iterate| MAT_eulog
    GRO_pow ==>|Invert| MAT_eulog["a [ ∥ b ]"]
    %% Expanded form `[ 4 ∥ 3 ]` -> `Σ[ ¬(4 ◇ (3 ^ ℕ)) ]`
%% 
%% Ratios
    %% Visualizer: shows 2 numbers instead of 1, for numerator and denominator (4 numbers when complex)
    MAT_eudiv --o|Same Thing| RAT_ratio["a ⫽ b"]

    RAT_ratio ==>|Iterate| RAT_recip["[ 1⁄n ]"]
    %% Expanded form `(4/3) [ 1⁄n ]` -> `[ 3 ÷ 4 ]` 

    RAT_ratio ==>|Remainder| RAT_mod["a◇b"]
    %% Expanded form `[ 4 ◇ 3 ]` -> `[ 4 – (3 × (4 ⫽ 3)) ]`

    RAT_recip ==> RAT_div["a [ ÷ b ]"]
    %% Expanded form `[ 4 ÷ 3 ]` -> `[ 4 × (1⁄3) ]`    

    RAT_div ==> RAT_per["％"]
    %% Expanded form `[ (a÷100) × b ]` <-- should 100 change based on base setting? 
%% 
%% Music
    %% Music Mode: When toggled, result is normalized to [1/16, 16) and a sfx tone plays at result ×440 hz 
    RAT_div ==> MUS_whole["a ♩↑ b"]
    GRO_pow --o MUS_whole
    %% Expanded form `[ a × ((9 ÷ 8) ^ b) ]`
    RAT_recip ==> MUS_inter["a ⋮ b"]
    %% Expanded form `[ a × (1 + 1⁄b) ]`
    GRO_radical --o MUS_semit
    MUS_semit["a ♯↑ b"]
    %% Expanded form `[ a × (¹²√(2 ^ b)) ]`

%% 
    
    ROT_quarter --o RAT_cdiv
    RAT_mod ==>|Complex_Tuple| RAT_cdiv["a⨸b"]
    %% Expanded form `[ 4 ⨸ 3 ]` -> `[ (4 ⫽ 3) + i × (4 ◇ 3) ]`
%% Growth
    %% Visualizer: Not set in stone yet. Cobweb plot? 
    MAT_eulog --o|Same Thing| GRO_dislog["a [ ∥ b ]"]

    RAT_recip --o GRO_sqrt
    GRO_dislog ==> GRO_sqrt["[ ²√n ]"]
    %% Expanded form `[ ²√(4) ]` -> `[ 2 ^ ((4 ∥ 2) ÷ 2) ]`
        
    GRO_sqrt ==>|Invert| GRO_radical["[ ᵇ√a ]"]
    %% Expanded form `[ ³√(4) ]` -> `[ 3 ^ (1 ÷ 3) ]`

    GRO_dislog ==>|Remainder| GRO_resid["a [ ⟐ b ]"]
    %% Expanded form `[ 4 ⟐ 3 ]` -> `[ 4 ÷ (3 ^ (4 ∥ 3)) ]`

    ROT_quarter --o GRO_clog["a ⦷ b"]
    GRO_resid ==>|Complex_Tuple| GRO_clog
    %% Expanded form `[ 4 ⦷ 3 ]` -> `[ (4 ∥ 3) + i × (4 ⟐ 3) ]`

    GRO_radical ===|Invert?| GRO_log["n [ ℓ ]"]
    %% Primitive?
    %% Expanded form `[ ℓ4 ]` -> `[ dirivitive(1/4) ]`
    %% Expanded form `[ ℓ4 ]` -> `[ lim{h->0}((4^h - 1)/h) ]`
    %% Expanded form `[ ℓ4 ]` -> `[ Σ{h=ℕ}(((-1)^(h+1))×(4^h))/(h) ]`

%%  
%% Rotation
    %% Visualizer: circle, which is similar to the cartesian visualizer but projects down to the unit circle to only focus on rotation.
    %% VITAL UX: make it abundantly clear that each rotation "unit" is 1/24 of a circle, or pi/12 radians. The math behind the scenes will be (n × e^(i*2pi*(n/24)))
    
    
    ROT_twentyfourth["[ n ⦨ ]"]
    %% Primitive
    %% Expanded form `[ 4 ⦨ ]` -> `[ 4 × e^(iπ/12) ]`
    %% Expanded form `[ 4 ⦨ ]` -> `[ -0:30 ]`
    ROT_twentyfourth ==>|Iterate| ROT_rotate["a [ ↶ b ]"]
    %% Expanded form `[ 4 ↶ 3 ]` -> `[ 4 × e^{i×2π×(3/24)} ]`
    %% Expanded form `[ 4 ↶ 3 ]` -> `[ 4 ⦨ ⦨ ⦨ ]`
    %% Expanded form `[ 4 ↶ 3 ]` -> `[ -1:30 ]`
    ROT_rotate ==> ROT_quarter["[ n ↶ ⦜ ]"]
    GRO_sqrt --o ROT_quarter
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ 4 × √(-1) ]`
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ 4 ↶ 6 ]`
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ 4 ⦨ ⦨ ⦨ ⦨ ⦨ ⦨ ]`
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ -3:00 ]`
    ROT_rotate ==> ROT_half["n [ ± ]"]
    %% Expanded form `[ 4 ± ]` -> `[ ⦜ ⦜ ]`
    %% Expanded form `[ 4 ± ]` -> `[ 4 ↶ 12 ]`
    %% Expanded form `[ 4 ± ]` -> `[ 4 × -1 ]`

    BOO_sign --o ROT_modulus["z [ |z| ]"]
    ROT_half ==> ROT_modulus
    BOO_ifelse --o ROT_modulus
    %% %% Expanded form `[ |4| ]` -> `[ ¬(4 × ⨩(4)) ⩣ (4 × ⨩(4)) ]`
    %% GRO_radical --o ROT_modulus
    %% ROT_norm ==> ROT_modulus["z [ |z| ]"]
    %% Expanded form `[ |4| ]` -> `[ √(Re(4)² + Im(4)²) ]

    ROT_modulus ==> ROT_conj["z̄"]
    %% Expanded form `[ (|z|^2) / z ]`
    ROT_conj ==> ROT_impart["[ Im(z) ]"]
    %% %% Ixpanded form `[ Im(z) ]` -> `[ (z - z̄) / 2i ]`
    ROT_impart === ROT_repart["[ Re(z) ]"]
    %% %% Expanded form `[ Re(z) ]` -> `[ (z + z̄) / 2 ]`

    
    ROT_conj ==> ROT_norm["z [ ||z|| ]"]
    %% Expanded form `[ |4| ]` -> `[ z × z̄ ]
    
    ROT_rotate ==>|Invert| ROT_theta
    GRO_log --o ROT_theta["z [ θ⦨ ]"]
    %% %% Expanded form `[ z θ⦨ ]` -> `[ (12 ÷ π) × ℓ(z ÷ |z|)]`

    ROT_theta ==> ROT_c_tuple["z ⦾"]
    %% Expanded form `[ z ⦾ ]` -> `[ ||z|| + (i × θ⦨(z)) ]`
%% 
%% Logic
    %% Visualizer: default again, but in binary mode
    %% For logic operators, NaN is treated as False (represented as ⊥ in expansions), and any value (including 0) is treated as true
    %% a, b, n -> numeric values (else false)
    %% p, q -> numeric values (true) or ⊥ (false)
    
    RAT_mod --> BOO_divis["a | b"]
    
    MAT_eudiv --o|Div-0| BOO_notp["¬ p"]
    %% Expanded form `[ ⊥ if p, else 1 ]`
    BOO_notp === BOO_ifelse["p ⩣ q"]
    %% Expanded form `[ p if p, else q ]`

    RAT_div --o BOO_sign["n ⨩ "]
    %% Expanded form `[ n ÷ ((n ÷ n) – 1)  ]`
    BOO_sign ==> BOO_less["a < b"]
    %% Expanded form `[ ⨩(a – b) ]`

    BOO_eq ==> BOO_divis
    %% Expanded form `[ (a ◇ b) ≡ 0) ]`

    BOO_ifelse ==> BOO_or["p ∨ q"]
    %% Expanded form `[ ¬¬(p ⩣ q) ]`
    BOO_or ==> BOO_and["p ∧ q"]
    %% Expanded form `[ ¬(¬p ∨ ¬q) ]`
    
    BOO_notp ==> BOO_eq["a ≡ b"]
    %% Expanded form `[ ¬¬(1 / (a - b)) ]`
    BOO_or ==> BOO_notgt
    BOO_less ==> BOO_notgt["a ≤ b"]
    BOO_eq ==> BOO_notgt
    %% Expanded form `[ (a < b) ∨ (a ≡ b) ]`

    BOO_notgt ==> BOO_max["a ⫨ b"]
    %% Expanded form `[ ((a < b) × b) ⩣ ¬((a ≤ b) × a) ]`
    BOO_notgt ==> BOO_minim["a ⫧ b"]
    %% Expanded form `[ ((a < b) × a) ⩣ ¬((a ≤ b) × b) ]`
%% 
%% Primes
    %% Still conceptual - has a lot of functions designed, but the way the user will interact with these is not planned yet
    %% Visualizer: prime factorization, not sure what else would be interesting
    
    %% DOM_prime --> Pnthprime["ℙ(n)"]
    %% %% Primitive
    %% %% Returns nth prime. ℙ(3) = 5
    %% Pnthprime -->|Invert| Pindexofp["ℕ(p)"]
    %% %% Returns index of prime p. ℙ^-1(5) = 3

    %% Pnthprime --> Padic["v_p(n)"]
    %% MAT_eulog --> Padic
    %% %% Expanded form `[ n ∥ ℙ(3) ]`
    %% Padic --> Pprime_expansion("∏ ℙ^e")

    %% %% Expanded form `n ∥ ℙ("⟐
    %% Padic --> Pomega["Ω(n)"]
    %% GRO_resid --> Pomega
    %% %% n=60
    %% %% r=15,5,1
    %% %% s=2,1,1,0
    %% %% x=1,2,3,4
    %% %% Expanded form `r=60 ∥ ℙ(x=1) = s=2`
    %% %% Expanded form `r=60 ⟐ ℙ(x=1) = 15`
    %% %% Expanded form `r=60 ⟐ ℙ(x=1) ∥ ℙ(x=2) = s=1`
    %% %% Expanded form `r=15 ⟐ ℙ(x=2) = 5`
    %% %% Expanded form `r=15 ⟐ ℙ(x=2) ∥ ℙ(x=3) = s=1`
    %% %% Expanded form `r=5 ⟐ ℙ(x=3) = 1`
    %% %% Expanded form `r=5 ⟐ ℙ(x=3) ∥ ℙ(x=4) = s=0`
    %% %% Expanded form `r=1 ⟐ ℙ(x=4) = 1`
    %% %% Expanded form `Σ{x=1..n}[ ((x - 1) ⟐ ℙ(x - 1)) ∥ ℙ(x) ]`
    %% Ptotient["φ"]
    %% %% Expanded form `[ n × ∏(1-p^-1) ]`
    %% BOO_divis --> Pdivisor_sum["σ"]
    %% %% Expanded form `[ Σ( (d|n) × d) ]`
    %% RAT_mod --> Pgcd
    %% ROT_impart --> Pgcd["n ⩑"]
    %% %% %% Old:Expanded form `[ ∏p^(e_a ⫧ e_b) ]`
    %% %% Expanded form `[ Im(n) + (i × (Re(n) ◇ Im(n))) ]`
    %% Pgcd --> Plcm["⩒"]
    %% %% Expanded form `[" ∏p^(e_a ⫨ e_b) "]`    
%% 

%%     subgraph Digits ["Digit Manipulation"]
%%     %% Currently a dead-end; could lead to more complex cycles
%%         Ddig["a⪼b"]
%%         %% Primitive, takes last b digits of a (respects base setting)
%%         %% Expanded form `[ a◇(10^b) ]` <-- 10 changes with base
%%         Ddigitn["a#b"]
%%         %% Expanded form `[ a⪼b - a⪼(b-1) ÷ 10^(b-1)) ]` <--- 10 changes with base
%%         Ddigsum["dΣn"]
%%         %% Expanded form `[ ..d#3 + d#2 + d#1 ] <--- as many entries as digits in operand (respecting current base)
%%         Ddigsq["d²Σn"]
%%         %% Expanded form `[ ..(d#2)^2 + (d#1)^2 ] <--- as many entries as digits in operand (respecting current base)
%%         Dsort["d⇡n"]
%%         Drotate["a⟲b"]
%%         Dcount["d##n"]
%%         Dmirror["d⇋n"]
%%     end
%%     Ddig -->|Generalize| Ddigitn
%%     Ddigitn --> Dcount
%%     Dcount --> Ddigsum
%%     Dcount --> Ddigsq
%%     Dsort --> Drotate
%%     Dsort --> Dmirror
%%     BOO_notgt --> Digits
%%     RAT_mod --> Ddig
%% Pnthprime > Ptotient
%% Snthp-ime --> Pindexofp
%% Pprime_expansion --t Pomega
%% Pindexofp --> Pprime_expansion
%% Pnthprime --> Pgcd
%% Pexponent --> Pgcd
%% Pexponent --> Plcm
%% Pnthprime --> Plcm
%% Pnthprime --> Pexponent
%% BOO_minim --> Plcm
%% BOO_max --> Pgcd