%% Truth 4: Keep

%% ⋕
%% Design guidelines:
%% 1. All operators can be constructed from atomic primitives
%% 2. Operators can be unary (takes previous operator result) or binary (takes previous operator result and second operand)
%% 3. User enters initial seed value, operators, and binary operands. A combination operator and second operand are a "operation slot"
%% 4. Values for seeds and binary operands can be digits 0-9
%% 
%% Theoretical progression path:
%% - Every subgraph defines its own calculator, which starts with its own settings, primitives, and visualizer locked in place (at first).
%% - Every calculator is equipped with the settings required to reason about that family of operators and intuitively understand the results.
%% - The player starts with the increment operator only, and must construct other operators to earn the right to think that way.

flowchart TD

    subgraph Identities ["n"]
        Iprime
        Inat
        Irat
        Iint
        Irad
        Iimag
        Icomp

        Ierr
        Ifalse

        Imulneg
        Imulimag
        Inegroot
        Iaddimag
        Ipythag
        Inodivisor

    subgraph Boolean_Ops ["1/0"]

        Bnotp
        Bifelse
        Band
        Bor

        subgraph Comparisons ["≤"]
        Bnotgt
        Bless
        Beq
        Bdivis
        Bmax
        Bminim
        Bminmaxtuple
        end
    end

    subgraph Linear_Ops
        Linc
        Ldec

        Lminus
        Lplus

        %% Lfloor
        %% Lceil
    end

    subgraph Magnitude_Ops
        Mdivtuple
        Mmod
        Meudiv
        Mmul
        Mdiv
        Mper
        Mrecip
        Mneg
        
    end

    subgraph Exponential_Ops    
        Epow
        Eradical
        Elog   
        
        Elog_tuple
        Eeulog
        Eresid        
    end

    subgraph Rotation_Ops ["× 𝕀"]

        Rtwentyfourth
        Rrotate
        Rquarter
        %% Rc_tuple
        %% Rtheta
        Rtrig("trig")

        Rconj

        Rimpart
        Rrepart
        Rmodulus
    end     

    subgraph P_Theory ["Returns ℙ (2)"]
        Pnthprime
        Pindexofp

        Padic
        Pprime_expansion

        Pomega        
        Ptotient
        Pdivisor_sum
        
        Pgcd
        Plcm
    end
    end


%% Identities
    %% Visualizer: default (real ints)
    
    Inat{"ℕ"}

    Lminus --> Iint{"ℤ"}

    Mdiv --> Irat{"ℚ"}

    Eradical --> Irad{"𝔸‾"}

    Irad --> Inegroot
    Lminus --> Inegroot("√-1")
    Inegroot --> Iimag{"𝕀"}

    Iimag --> Iaddimag
    Lplus --> Iaddimag("1 + √-1")
    Iaddimag --> Icomp{"ℂ"}

    Icomp --> Ipythag("√(1^2 + i^2)")

    Inat --> Inodivisor
    Mmod --> Inodivisor("¬(n ◇ ℕ{2..n} ≡ 0)")
    Inodivisor --> Iprime{ℙ}
    

    Mdiv --> Ierr
    Iint --> Ierr(n ÷ 0)
    Ierr --> Ifalse{𝕋/𝔽}
    
    Mmul --> Imulneg
    Iint --> Imulneg(n × -1)

    Mmul --> Imulimag
    Iimag --> Imulimag(n × i)
%% 
%% Linear
    %% Visualizer: cartesian plane (numberline when dealing with reals, then plane for complex numbers)
    
    Inat --> Linc["[ n ++ ]"]
    %% Primitive
    %% Expanded form `[ 4 ++ ]` -> `[ 4 ℕ{..3 4◌⃕5..} ]`
    %% Completes ℕ on its own
    Linc -->|Invert| Ldec["[ n -- ]"]
    %% Expanded form `[ 4 –– ]` -> `[ 4 ℤ{..3◌⃔4 5..} ]`
    %% Expanded form `[ 4 –– ]` -> `[ 4 ++⮌ ]`
    %% Completes ℤ with ++
    Linc -->|Iterate| Lplus["a [ \+b ]"]
    %% Expanded form `[ 4 + 3 ]` -> `[ 4 ++ ++ ++ ]`  
    Lplus -->|Invert| Lminus["a [ − b ]"]
    %% Expanded form `[ 4 - 3 ]` -> `[ 4 +⮌ 3 ]`
    Ldec -->|Iterate| Lminus["a [ − b ]"]
    %% Expanded form `[ 4 - 3 ]` -> `[ 4 –– –– –– ]`
    %% Mmod --> Lfloor["⌊n⌋"]
    %% %% Expanded form `[ ⌊(4/3)⌋ ]` -> `[ (4/3) - ((4/3) ◇ 1) ]`
    %% Lfloor --> Lceil["⌈n⌉"]
    %% %% Expanded form `[ ⌈(4/3)⌉ ]` -> `[ (4/3) + (1 - ((4/3) ◇ 1)) ]`
%% 
%% Magnitude
    %% Visualizer: function graph (points plotted on x=roll index, y=result)

    Mdiv -->|Invert| Mrecip["[ 1⁄n ]"]
    %% Expanded form `(4/3) [ 1⁄n ]` -> `[ 3 ÷ 4 ]` 
    
    Lplus -->|Iterate| Mmul["a [ × b ]"]
    %% Expanded form `[ 4 × 3 ]` -> `[ 4 +4 +4 ]`
    %% Rimpart --> Rmodulus
    %% Rrepart --> Rmodulus
    %% Rrotate -->|Iterate| Mneg["n±"]
    

    Mmul -->|Discrete| Mdivtuple("⫽ + ◇")

    Mdivtuple -->|Count| Meudiv["a⫽b"]
    %% Expanded form `[ 4 ⫽ 3 ]` -> `Σ[ ¬(4 – (3 × ℕ)) ]`

    Mdivtuple -->|Remainder| Mmod["a◇b"]
    %% Expanded form `[ 4 ◇ 3 ]` -> `[ 4 – (3 × (4 ⫽ 3)) ]`

    Mmul -->|Invert| Mdiv["a [ ÷ b ]"]
    %% Expanded form `[ 4 ÷ 3 ]` -> `[ 4 ×⮌ 3 ]`    

    Mdiv --> Mper["％"]
    %% Expanded form `[ (a÷100) × b ]` <-- should 100 change based on base setting? 
    
    Imulneg --> Mneg["n [ ± ]"]
    %% Expanded form `[ 4 ± ]` -> `[ 4 × -1 ] ]`

    %% More division and fraction-related operations:
    %% probability (ie, random number generator)
    %% average 2 numbers
    %% mediant?
%% 
%% Growth
    %% Visualizer: Not set in stone yet. Cobweb plot? 
    Mmul -->|Iterate| Epow["a [ ^ b ]"]
    %% Expanded form `[ 4 ^ 3 ]` -> `[ 4 ×4 ×4 ]`

    Epow -->|Discrete| Elog_tuple("∥ × ⟐")

    Elog_tuple -->|Count| Eeulog["a [ ∥ b ]"]
    %% Expanded form `[ 4 ∥ 3 ]` -> `Σ[ ¬(4 ◇ (3 ^ ℕ)) ]`

    Elog_tuple -->|Remainder| Eresid["a [ ⟐ b ]"]
    %% Expanded form `[ 4 ⟐ 3 ]` -> `[ 4 ÷ (3 ^ (4 ∥ 3)) ]`
        
    Epow -->|Invert| Eradical["[ ᵇ√a ]"]
    %% Expanded form `[ ³√(4) ]` -> `[ 4 ^ (1/3) ]`

    Epow -->|Invert2| Elog["n [ ℓ ]"]
    %% Primitive?
    %% Expanded form `[ ℓ4 ]` -> `[ dirivitive(1/4) ]`
    %% Expanded form `[ ℓ4 ]` -> `[ lim{h->0}((4^h - 1)/h) ]`
    %% Expanded form `[ ℓ4 ]` -> `[ Σ{h=ℕ}(((-1)^(h+1))×(4^h))/(h) ]`

%%  
%% Rotation
    %% Visualizer: circle, which is similar to the cartesian visualizer but projects down to the unit circle to only focus on rotation.
    %% VITAL UX: make it abundantly clear that each rotation "unit" is 1/24 of a circle, or pi/12 radians. The math behind the scenes will be (n × e^(i*2pi*(n/24)))
    Rtwentyfourth["[ n ⦨ ]"]
    %% Primitive
    %% Expanded form `[ 4 ⦨ ]` -> `[ 4 × e^(iπ/12) ]`
    %% Expanded form `[ 4 ⦨ ]` -> `[ -0:30 ]`
    Rtwentyfourth -->|Iterate| Rrotate["a [ ↶ b ]"]
    %% Expanded form `[ 4 ↶ 3 ]` -> `[ 4 × e^{i×2π×(3/24)} ]`
    %% Expanded form `[ 4 ↶ 3 ]` -> `[ 4 ⦨ ⦨ ⦨ ]`
    %% Expanded form `[ 4 ↶ 3 ]` -> `[ -1:30 ]`
    Rrotate --> Rquarter
    Imulimag --> Rquarter["[ n ↶ ⦜ ]"]
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ 4 × √(-1) ]`
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ 4 ↶ 6 ]`
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ 4 ⦨ ⦨ ⦨ ⦨ ⦨ ⦨ ]`
    %% Expanded form `[ 4 ↶ ⦜ ]` -> `[ -3:00 ]`

    Rmodulus --> Rconj["z̄"]
    %% Expanded form `[ (|z|^2) / z ]`
    Rconj --> Rimpart["[ Im(z) ]"]
    %% %% Ixpanded form `[ Im(z) ]` -> `[ (z - z̄) / 2i ]`
    Rconj --> Rrepart["[ Re(z) ]"]
    %% %% Expanded form `[ Re(z) ]` -> `[ (z + z̄) / 2i ]`

    Ipythag --> Rmodulus["z [ |z| ]"]
    %% Expanded form `[ |4| ]` -> `[ √(Re(4)² + Im(4)²) ]
    %% Mneg --> Rmodulus
    %% Bnotp --> Rmodulus["z [ |z| ]"]
    %% %% Expanded form `[ |4| ]` -> `[ ¬(4) × ±(4) ] + [ ¬¬(4) × (4)  ]`
    
    %% Rrotate --> Rc_tuple("|z| + θ")
    
    %% Rc_tuple --> Rtheta["z [ θ ]"]
    %% %% Expanded form `[ z θ ]` -> `[ ln(z{6+7i}/|{6+7i}|)/√(-1)]`
%% 
%% Logic
    %% Visualizer: default again, but in binary mode
    %% For logic operators, NaN is treated as False (represented as ⊥ in expansions), and any value (including 0) is treated as true
    %% a, b, n -> numeric values (else false)
    %% p, q -> numeric values (true) or ⊥ (false)
    
    Mmod --> Bdivis["a | b"]
    Beq --> Bdivis
    %% Expanded form `[ (a ◇ b) ≡ 0) ]`
    
    Ifalse --> Bnotp["¬ p"]
    %% Expanded form `[ 1 if n, else ⊥ ]`
    Ifalse --> Bifelse["p ⩣ q"]
    %% Expanded form `[ p if p, else q ]`

    Bnotp --> Bor
    Bifelse --> Bor["p ∨ q"]
    %% Expanded form `[ ¬¬(p ⩣ q) ]`
    Bor --> Band["p ∧ q"]
    %% Expanded form `[ ¬(¬p ∨ ¬q) ]`
    
    Bnotp --> Beq["a ≡ b"]
    %% Expanded form `[ ¬¬(1 / (a - b)) ]`
    Rmodulus --> Bless["a < b"]
    %% Expanded form `[ ¬¬(1 / ((b - a) + |b - a|)) ]`
    Beq --> Bnotgt
    Bless --> Bnotgt["a ≤ b"]
    Bor --> Bnotgt
    %% Expanded form `[ (a < b) ∨ (a ≡ b) ]`

    Bnotgt --> Bminmaxtuple
    Bifelse --> Bminmaxtuple("⫧, ⫨")
    Bminmaxtuple --> Bmax["a ⫨ b"]
    %% Expanded form `[ ((a < b) × b) ⩣ ¬((a ≤ b) × a) ]`
    Bminmaxtuple --> Bminim["a ⫧ b"]
    %% Expanded form `[ ((a < b) × a) ⩣ ¬((a ≤ b) × b) ]`
%% 
%% Primes
    %% Still conceptual - has a lot of functions designed, but the way the user will interact with these is not planned yet
    %% Visualizer: prime factorization, not sure what else would be interesting
    
    Iprime --> Pnthprime["ℙ(n)"]
    %% Primitive
    %% Returns nth prime. ℙ(3) = 5
    Pnthprime -->|Invert| Pindexofp["ℕ(p)"]
    %% Returns index of prime p. ℙ^-1(5) = 3

    Pnthprime --> Padic["v_p(n)"]
    Eeulog --> Padic
    %% Expanded form `[ n ∥ ℙ(3) ]`
    Padic --> Pprime_expansion("∏ ℙ^e")

    %% Expanded form `n ∥ ℙ("⟐
    Padic --> Pomega["Ω(n)"]
    Eresid --> Pomega
    %% n=60
    %% r=15,5,1
    %% s=2,1,1,0
    %% x=1,2,3,4
    %% Expanded form `r=60 ∥ ℙ(x=1) = s=2`
    %% Expanded form `r=60 ⟐ ℙ(x=1) = 15`
    %% Expanded form `r=60 ⟐ ℙ(x=1) ∥ ℙ(x=2) = s=1`
    %% Expanded form `r=15 ⟐ ℙ(x=2) = 5`
    %% Expanded form `r=15 ⟐ ℙ(x=2) ∥ ℙ(x=3) = s=1`
    %% Expanded form `r=5 ⟐ ℙ(x=3) = 1`
    %% Expanded form `r=5 ⟐ ℙ(x=3) ∥ ℙ(x=4) = s=0`
    %% Expanded form `r=1 ⟐ ℙ(x=4) = 1`
    %% Expanded form `Σ{x=1..n}[ ((x - 1) ⟐ ℙ(x - 1)) ∥ ℙ(x) ]`
    Ptotient["φ"]
    %% Expanded form `[ n × ∏(1-p^-1) ]`
    Bdivis --> Pdivisor_sum["σ"]
    %% Expanded form `[ Σ( (d|n) × d) ]`
    Pprime_expansion --> Pgcd
    Irat --> Pgcd["⩑"]
    %% Expanded form `[ ∏p^(e_a ⫧ e_b) ]`
    Pgcd --> Plcm["⩒"]
    %% Expanded form `[" ∏p^(e_a ⫨ e_b) "]`    
%% 

%%     subgraph Digits ["Digit Manipulation"]
%%     %% Currently a dead-end; could lead to more complex cycles
%%         Ddig["a⪼b"]
%%         %% Primitive, takes last b digits of a (respects base setting)
%%         %% Expanded form `[ a◇(10^b) ]` <-- 10 changes with base
%%         Ddigitn["a#b"]
%%         %% Expanded form `[ a⪼b - a⪼(b-1) ÷ 10^(b-1)) ]` <--- 10 changes with base
%%         Ddigsum["dΣn"]
%%         %% Expanded form `[ ..d#3 + d#2 + d#1 ] <--- as many entries as digits in operand (respecting current base)
%%         Ddigsq["d²Σn"]
%%         %% Expanded form `[ ..(d#2)^2 + (d#1)^2 ] <--- as many entries as digits in operand (respecting current base)
%%         Dsort["d⇡n"]
%%         Drotate["a⟲b"]
%%         Dcount["d##n"]
%%         Dmirror["d⇋n"]
%%     end
%%     Ddig -->|Generalize| Ddigitn
%%     Ddigitn --> Dcount
%%     Dcount --> Ddigsum
%%     Dcount --> Ddigsq
%%     Dsort --> Drotate
%%     Dsort --> Dmirror
%%     Bnotgt --> Digits
%%     Mmod --> Ddig
%% Pnthprime > Ptotient
%% Snthp-ime --> Pindexofp
%% Pprime_expansion --t Pomega
%% Pindexofp --> Pprime_expansion
%% Pnthprime --> Pgcd
%% Pexponent --> Pgcd
%% Pexponent --> Plcm
%% Pnthprime --> Plcm
%% Pnthprime --> Pexponent
%% Bminim --> Plcm
%% Bmax --> Pgcd