%% Truth 4: Keep

flowchart TD

subgraph Numbers ["Numbers"]

    subgraph Digits ["Digit Manipulation"]
    %% Currently a dead-end; could lead to more complex cycles
        Ddig["a⪼b"]
        %% Primitive, takes last b digits of a (respects base setting)
        %% Expanded form `[ a◇(10^b) ]`
        Ddigitn["a#b"]
        %% Expanded form `[ a⪼b - a⪼(b-1) ÷ 10^(b-1)) ]` <--- "10" changes respecting base
        Ddigsum["dΣn"]
        %% Expanded form `[ ..d#3 + d#2 + d#1 ] <--- as many entries as digits in operand (respecting current base)
        Ddigsq["d²Σn"]
        %% Expanded form `[ ..(d#2)^2 + (d#1)^2 ] <--- as many entries as digits in operand (respecting current base)
        Dsort["d⇡n"]
        Drotate["a⟲b"]
        Dcount["d##n"]
        Dmirror["d⇋n"]

        Ddig -->|Generalize| Ddigitn
        Ddigitn --> Dcount
        Dcount --> Ddigsum
        Dcount --> Ddigsq
        Dsort --> Drotate
        Dsort --> Dmirror
    end

    subgraph Logic ["Logical Predicates"]
        Lnot["¬n"]
        %% Primitive
        Llte["a≤b"]
        %% Expanded form `[ ¬(a-b) ]
        Llt["a\< b"]
        %% Expanded form `[ (a≤b) × ¬(¬(a-b))]
        Ldiv["a|b"]
        %% Expanded form `[ ¬(a◇b) ]
        Leq["a≡b"]
        %% Expanded form `[ ¬((a<b) + (b<a)) ]
        Lmax["╧"]
        %% Expanded form `[ ((a<b)×b) + ¬((a≤b)×a) ]`
        Lmin["╤"]  
        %% Expanded form `[ ((a<b)×a) + ¬((a≤b)×b) ]`

        Lnot --> Llte --> Llt
        Lnot --> Ldiv
        Llt --> Leq
        Llt --> Lmin
        Llt --> Lmax
    end

    subgraph Arithmetic ["ℕ (1) | ℤ (-1)"]
        Ainc["++"]
        %% Primitive
        Aminus["a−b"]
        Aplus["a\+b"]
        Amul["a×b"]
        Apow["a^b"]
        Aneg["n±"]
        Aeudiv["a⫽b"]
        %% Primitive
        Apadic["n∥p"]
        %% Primitive
        Amod["a◇b"]
        %% Expanded form `[ a - (b×(a⫽b)) ]`
        Ares["a⟐b"]
        %% Expanded form `[ a ÷ b^(a∥b) ]` <--- I am not sure if I am pointing at anything coherent
        %% Expanded form `[ 10 ÷ 2^(10∥2) ]`
        %% Expanded form `[ 10 ÷ 2^(1) ]`
        %% Expanded form `[ 10⟐2 = 5 ]` 
        %% Expanded form `[ 15⟐2 = 15 ]` 
        %% Expanded form `[ 15⟐4 = 15 ]` 
        %% Expanded form `[ 20⟐4 = 5 ]` 
        Afloor["⌊n⌋"]
        %% Expanded form `[ a-a◇1 ]`
        Aceil["⌈n⌉"]
        %% Expanded form `[ ⌊n⌋++ ]`

        Afloor --> Aceil
        Amod --> Afloor

        Ainc -->|Iterate| Aplus -->|Iterate| Amul -->|Iterate| Apow

        Aplus -->|Invert| Aminus
        Amul -->|Invert| Aeudiv --> Amod
        Apow -->|Invert| Apadic --> Ares

        Aminus --> Aneg

        subgraph Reduction ["ℚ&𝔸"]

            Rdiv["a÷b"]
            %% Expanded form `[ a × (1/b) ]
            Rper["%"]
            %% Expanded form `[ (a÷100) × b ]
            Rradical["b√a"]
            %% Might need a better operator glyph
            %% Expanded form `[ a ^ (1/b)]

            Rdiv --> Rper

            subgraph ComplexAlgebra ["ℂ×ℚ = {q + c × √-1 | a,b ∈ ℚ}"]
                Ciunit["n×i"]
                %% Primitive
                %% Expanded form `[ × √-1 ]`
                Cradian["n×2π"]
                Cimag["Im(n)"]
                %% Returns the imaginary component (`b` from `a + b×i`) from part of n, 0 possible
                Creal["Re(n)"]
                %% Returns the non-imaginary component (`a` from `a + b×i`) from part of n, 0 possible
                Cmodulus["|n|"]
                %% Expanded form `[ √(Im^2 + Re^2) ]`

                Ciunit --> Cimag --> Cmodulus
                Ciunit --> Creal --> Cmodulus
                Ciunit --> Cradian --> Trig
            end
            Rradical --> Ciunit
        end
        Amul -->|Invert| Rdiv
        Apow -->|Invert| Rradical
        Aneg --> Ciunit
        Amod -->|a◇inf| Cradian
        %% It's conceptual, just go with it for now
    end

    subgraph Theory ["ℙ (2)"]
    %% Has a lot of functions designed, but the way the user will interact with these is not planned yet

        Tntop["ℙ(n)"]
        %% Primitive
        %% Returns nth prime. ℙ(3) = 5
        Tpton["ℙ^-1(p)"]
        %% Returns index of prime p. ℙ^-1(5) = 3
        Texponent["e"]
        Tprime_expansion["∏ ℙ^e"]
        Tomega["Ω"]
        %% Expanded form `[ Σe_p ]`
        Ttotient["φ"]
        %% Expanded form `[ n × ∏(1-p^-1) ]`
        Tdivisor_sum["σ"]
        %% Expanded form `[ Σ( (d|n) × d) ]`
        Tgcd["⋀"]
        %% Expanded form `[ ∏p^(e_a ╤ e_b) ]`
        Tlcm["⋁"]
        %% Expanded form `[ ∏p^(e_a ╧ e_b) ]`

        Tntop --> Ttotient

        Tntop --> Tpton
        Tprime_expansion --> Tomega
        Tpton --> Tprime_expansion
        Texponent --> Tgcd
        Tntop --> Tgcd

        Tntop --> Tlcm
        Texponent --> Tlcm
        Tntop --> Texponent
    end
Lmin --> Tlcm
Lmax --> Tgcd
Amod --> Ldiv
Llte --> Digits
Amod --> Digits
Aminus --> Logic
Amul --> Logic
Aplus --> Logic
end

