import { KEY_ID } from "../domain/keyPresentation.js";
import {
  BINARY_ADD_RESULT_ONE_SEEN_ID,
  BINARY_MUL_RESULT_ZERO_SEEN_ID,
  C_CLEARED_FUNCTION_TWO_SLOTS_SEEN_ID,
  LAMBDA_POINTS_AWARDED_SEEN_ID,
  LAMBDA_POINTS_REFUNDED_SEEN_ID,
  LAMBDA_POINTS_SPENT_SEEN_ID,
  NAN_RESULT_SEEN_ID,
  OVERFLOW_ERROR_IN_BINARY_MODE_SEEN_ID,
} from "../domain/state.js";
import type { UnlockDefinition } from "../domain/types.js";

export const unlockCatalog: UnlockDefinition[] = [
  {
    id: "unlock_4_on_linear_growth_run_7",
    description: "Unlock 4 after a linear growth run of length 7.",
    predicate: { type: "roll_ends_with_growth_order_run", order: "linear", length: 7 },
    effect: { type: "unlock_digit", key: KEY_ID.digit_4 },
    sufficientKeySets: [[KEY_ID.op_add, "digit_nonzero"], [KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "I4_unlock",
    targetLabel: "4",
  },
  {
    id: "unlock_plus_on_linear_growth_run_7",
    description: "Unlock + after a linear growth run of length 7.",
    predicate: { type: "roll_ends_with_growth_order_run", order: "linear", length: 7 },
    effect: { type: "unlock_slot_operator", key: KEY_ID.op_add },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Aplus_unlock",
    targetLabel: "+",
  },
  {
    id: "unlock_mul_on_positive_constant_step_run_7",
    description: "Unlock × after constant-step linear growth with |step|>1 for 7 rows.",
    predicate: { type: "roll_ends_with_constant_step_run", length: 7, minAbsStep: 2n },
    effect: { type: "unlock_slot_operator", key: KEY_ID.op_mul },
    sufficientKeySets: [[KEY_ID.op_add, "digit_nonzero"]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Amul_unlock",
    targetLabel: "×",
  },
  {
    id: "unlock_pow_on_exponential_growth_run_7",
    description: "Unlock ^ after an exponential growth run of length 7.",
    predicate: { type: "roll_ends_with_growth_order_run", order: "exponential", length: 7 },
    effect: { type: "unlock_slot_operator", key: KEY_ID.op_pow },
    sufficientKeySets: [[KEY_ID.op_mul, "digit_nonzero"]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Apow_unlock",
    targetLabel: "^",
  },
  {
    id: "unlock_dec_on_total_at_least_10",
    description: "Unlock -- the first time a roll entry is lower than the previous entry.",
    predicate: { type: "roll_ends_with_constant_step_run", length: 2, requireNegativeStep: true },
    effect: { type: "unlock_slot_operator", key: KEY_ID.unary_dec },
    sufficientKeySets: [[KEY_ID.op_add, "digit_nonzero"], [KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Adec_unlock",
    targetLabel: "--",
  },
  {
    id: "unlock_inc_on_total_at_least_10",
    description: "Unlock ++ when total reaches at least 10.",
    predicate: { type: "total_at_least", value: 10n },
    effect: { type: "unlock_slot_operator", key: KEY_ID.unary_inc },
    sufficientKeySets: [[KEY_ID.op_add, "digit_nonzero"]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ainc_unlock",
    targetLabel: "++",
  },
  {
    id: "unlock_step_expansion_on_total_at_least_10",
    description: "Unlock [ ??? ] when total reaches at least 10.",
    predicate: { type: "total_at_least", value: 10n },
    effect: { type: "unlock_utility", key: KEY_ID.toggle_step_expansion },
    sufficientKeySets: [[KEY_ID.op_add, "digit_nonzero"], [KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ustep_expansion_unlock",
    targetLabel: "[ ??? ]",
  },
  {
    id: "unlock_minus_on_negative_total",
    description: "Unlock - on a run of 7 with negative slope.",
    predicate: { type: "roll_ends_with_constant_step_run", length: 7, requireNegativeStep: true },
    effect: { type: "unlock_slot_operator", key: KEY_ID.op_sub },
    sufficientKeySets: [[KEY_ID.unary_dec]],
    once: true,
    domainNodeId: "NZ",
    targetNodeId: "Aminus_unlock",
    targetLabel: "-",
  },
  {
    id: "unlock_neg_on_opposite_pair_cycle",
    description: "Unlock ± when an opposite-value 2-cycle is detected.",
    predicate: { type: "roll_cycle_is_opposite_pair" },
    effect: { type: "unlock_slot_operator", key: KEY_ID.unary_neg },
    sufficientKeySets: [[KEY_ID.op_sub, "digit_nonzero"]],
    once: true,
    domainNodeId: "NZ",
    targetNodeId: "Aneg_unlock",
    targetLabel: "±",
  },
  {
    id: "unlock_c_on_first_error",
    description: "Unlock C on first encountered error.",
    predicate: { type: "any_error_seen" },
    effect: { type: "unlock_utility", key: KEY_ID.util_clear_all },
    sufficientKeySets: [[KEY_ID.op_div, KEY_ID.digit_0], [KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Uc_unlock",
    targetLabel: "C",
  },
  {
    id: "unlock_div_on_negative_step_run_to_zero",
    description: "Unlock ÷ on a negative constant-step run (|step|>1) ending at 0.",
    predicate: {
      type: "roll_ends_with_constant_step_run",
      length: 7,
      minAbsStep: 2n,
      requireNegativeStep: true,
      endValue: 0n,
    },
    effect: { type: "unlock_slot_operator", key: KEY_ID.op_div },
    sufficientKeySets: [[KEY_ID.op_sub, "digit_nonzero"]],
    once: true,
    domainNodeId: "NQ",
    targetNodeId: "Adiv_unlock",
    targetLabel: "÷",
  },
  {
    id: "unlock_euclid_div_on_first_rational_result",
    description: "Unlock # the first time a rational non-integer result appears in the roll.",
    predicate: { type: "roll_contains_domain_type", domainType: "rational_non_integer" },
    effect: { type: "unlock_slot_operator", key: KEY_ID.op_euclid_div },
    sufficientKeySets: [[KEY_ID.op_div, "digit_nonzero"]],
    once: true,
    domainNodeId: "NQ",
    targetNodeId: "Aeuclid_unlock",
    targetLabel: "#",
  },
  {
    id: "unlock_calculator_g_on_tail_powers_of_two_run_7",
    description: "Unlock calculator g when the roll tail run of 7 contains only powers of 2.",
    predicate: { type: "roll_tail_powers_of_two_run", length: 7 },
    effect: { type: "unlock_calculator", calculatorId: "g" },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "G_unlock",
    targetLabel: "g",
  },
  {
    id: "award_lambda_to_f_on_transient_length_gt_10",
    description: "Award 1 λ to f the first time a transient length greater than 10 is found.",
    predicate: { type: "roll_cycle_transient_at_least", length: 11 },
    effect: { type: "increase_allocator_max_points_for_calculator", calculatorId: "f", amount: 1 },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Lf_transient_gt10",
    targetLabel: "λf+",
  },
  {
    id: "award_lambda_to_f_on_cycle_diameter_gt_10",
    description: "Award 1 λ to f the first time a cycle diameter greater than 10 is found.",
    predicate: { type: "roll_cycle_diameter_at_least", diameter: 11n },
    effect: { type: "increase_allocator_max_points_for_calculator", calculatorId: "f", amount: 1 },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Lf_cycle_diameter_gt10",
    targetLabel: "λf+",
  },
  {
    id: "award_lambda_to_f_on_cycle_length_gt_5",
    description: "Award 1 λ to f the first time a cycle length greater than 5 is found.",
    predicate: { type: "roll_cycle_period_at_least", length: 6 },
    effect: { type: "increase_allocator_max_points_for_calculator", calculatorId: "f", amount: 1 },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Lf_cycle_length_gt5",
    targetLabel: "λf+",
  },
  {
    id: "award_lambda_to_f_on_linear_growth_run_3_slope_gt_1",
    description: "Award 1 λ to f the first time a run of 3 has linear growth with slope > 1.",
    predicate: {
      type: "roll_ends_with_constant_step_run",
      length: 3,
      minAbsStep: 2n,
      requirePositiveStep: true,
    },
    effect: { type: "increase_allocator_max_points_for_calculator", calculatorId: "f", amount: 1 },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Lf_linear_run3_slope_gt1",
    targetLabel: "λf+",
  },
  {
    id: "award_lambda_to_f_on_exponential_growth_run_3",
    description: "Award 1 λ to f the first time a run of 3 has exponential growth.",
    predicate: { type: "roll_ends_with_growth_order_run", order: "exponential", length: 3 },
    effect: { type: "increase_allocator_max_points_for_calculator", calculatorId: "f", amount: 1 },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Lf_exponential_run3",
    targetLabel: "λf+",
  },
  {
    id: "award_lambda_to_g_on_binary_add_result_1",
    description: "Award 1 λ to g the first time + is used in base-2 mode and result is 1.",
    predicate: { type: "completed_unlock_id_seen", unlockId: BINARY_ADD_RESULT_ONE_SEEN_ID },
    effect: { type: "increase_allocator_max_points_for_calculator", calculatorId: "g", amount: 1 },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Lg_binary_add_1",
    targetLabel: "λg+",
  },
  {
    id: "award_lambda_to_g_on_binary_mul_result_0",
    description: "Award 1 λ to g the first time × is used in base-2 mode and result is 0.",
    predicate: { type: "completed_unlock_id_seen", unlockId: BINARY_MUL_RESULT_ZERO_SEEN_ID },
    effect: { type: "increase_allocator_max_points_for_calculator", calculatorId: "g", amount: 1 },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Lg_binary_mul_0",
    targetLabel: "λg+",
  },
  {
    id: "unlock_memory_plus_on_first_lambda_awarded",
    description: "Unlock λ⇒ the first time a lambda point is awarded.",
    predicate: { type: "completed_unlock_id_seen", unlockId: LAMBDA_POINTS_AWARDED_SEEN_ID },
    effect: { type: "unlock_memory", key: KEY_ID.memory_adjust_plus },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Mplus_unlock",
    targetLabel: "λ⇒",
  },
  {
    id: "unlock_memory_minus_on_first_lambda_spent",
    description: "Unlock λ⇐ the first time a lambda point is spent.",
    predicate: { type: "completed_unlock_id_seen", unlockId: LAMBDA_POINTS_SPENT_SEEN_ID },
    effect: { type: "unlock_memory", key: KEY_ID.memory_adjust_minus },
    sufficientKeySets: [[KEY_ID.memory_adjust_plus]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Mminus_unlock",
    targetLabel: "λ⇐",
  },
  {
    id: "unlock_memory_cycle_variable_on_first_lambda_spent",
    description: "Unlock α,β,γ the first time a lambda point is refunded.",
    predicate: { type: "completed_unlock_id_seen", unlockId: LAMBDA_POINTS_REFUNDED_SEEN_ID },
    effect: { type: "unlock_memory", key: KEY_ID.memory_cycle_variable },
    sufficientKeySets: [[KEY_ID.memory_adjust_minus]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Mcycle_unlock",
    targetLabel: "α,β,γ",
  },
  {
    id: "unlock_viz_eigen_allocator_on_first_lambda_refunded",
    description: "Unlock λ visualizer the first time a lambda point is refunded.",
    predicate: { type: "completed_unlock_id_seen", unlockId: LAMBDA_POINTS_REFUNDED_SEEN_ID },
    effect: { type: "unlock_visualizer", key: KEY_ID.viz_eigen_allocator },
    sufficientKeySets: [[KEY_ID.memory_adjust_plus]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Veigen_unlock",
    targetLabel: "λ",
  },
  {
    id: "unlock_viz_feed_on_roll_length_gt_20",
    description: "Unlock FEED the first time roll length exceeds 20.",
    predicate: { type: "roll_length_at_least", length: 21 },
    effect: { type: "unlock_visualizer", key: KEY_ID.viz_feed },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Vfeed_unlock",
    targetLabel: "FEED",
  },
  {
    id: "unlock_exec_play_pause_on_roll_length_gt_40",
    description: "Unlock ▶ the first time roll length exceeds 40.",
    predicate: { type: "roll_length_at_least", length: 41 },
    effect: { type: "unlock_execution", key: KEY_ID.exec_play_pause },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Eplay_unlock",
    targetLabel: "▶",
  },
  {
    id: "unlock_backspace_on_c_clears_function_two_slots",
    description: "Unlock ← the first time C clears a function with at least 2 committed operation slots.",
    predicate: { type: "completed_unlock_id_seen", unlockId: C_CLEARED_FUNCTION_TWO_SLOTS_SEEN_ID },
    effect: { type: "unlock_utility", key: KEY_ID.util_backspace },
    sufficientKeySets: [[KEY_ID.util_clear_all]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ubackspace_unlock",
    targetLabel: "←",
  },
  {
    id: "unlock_undo_on_first_nan_result",
    description: "Unlock ↩ the first time a NaN result is returned.",
    predicate: { type: "completed_unlock_id_seen", unlockId: NAN_RESULT_SEEN_ID },
    effect: { type: "unlock_utility", key: KEY_ID.util_undo },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Uundo_unlock",
    targetLabel: "↩",
  },
  {
    id: "unlock_roll_inverse_on_undo_while_feed_visible",
    description: "Unlock (=)⁻¹ when total reaches at least 10.",
    predicate: { type: "total_at_least", value: 10n },
    effect: { type: "unlock_execution", key: KEY_ID.exec_roll_inverse },
    sufficientKeySets: [[KEY_ID.util_undo, KEY_ID.viz_feed]],
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Einverse_unlock",
    targetLabel: "(=)⁻¹",
  },
  {
    id: "unlock_mod_on_first_cycle_length_gt_2",
    description: "Unlock ⟡ the first time a cycle with length greater than 2 is found.",
    predicate: { type: "roll_cycle_period_at_least", length: 3 },
    effect: { type: "unlock_slot_operator", key: KEY_ID.op_mod },
    sufficientKeySets: [[KEY_ID.unary_inc]],
    once: true,
    domainNodeId: "NQ",
    targetNodeId: "Amod_unlock",
    targetLabel: "⟡",
  },
  {
    id: "unlock_toggle_mod_zero_to_delta_on_binary_overflow",
    description: "Unlock ⟡[0, Δ) the first time overflow occurs in base-2 mode.",
    predicate: { type: "completed_unlock_id_seen", unlockId: OVERFLOW_ERROR_IN_BINARY_MODE_SEEN_ID },
    effect: { type: "unlock_utility", key: KEY_ID.toggle_mod_zero_to_delta },
    sufficientKeySets: [[KEY_ID.toggle_binary_mode]],
    once: true,
    domainNodeId: "NQ",
    targetNodeId: "Umod_zero_to_delta_unlock",
    targetLabel: "⟡[0,Δ)",
  },
];

