import type { UnlockDefinition } from "../domain/types.js";

export const unlockCatalog: UnlockDefinition[] = [
  {
    id: "unlock_equals_on_total_11",
    description: "Make no change.",
    predicate: { type: "roll_ends_with_equal_run", length: 2 },
    effect: { type: "unlock_execution", key: "=" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ut_exec_eq",
    targetLabel: "=",
  },
  {
    id: "unlock_plus_on_equal_run_4",
    description: "Count for a bit.",
    predicate: { type: "roll_ends_with_incrementing_run", length: 7, step: 1n },
    effect: { type: "unlock_slot_operator", key: "+" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Oplus",
  },
  {
    id: "unlock_1_on_plus_press_first",
    description: "Roll over.",
    predicate: { type: "total_magnitude_at_least", value: 10n },
    effect: { type: "unlock_digit", key: "1" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "I1_unlock",
    targetLabel: "1",
  },
  {
    id: "unlock_undo_on_total_at_least_20",
    description: "Restart.",
    predicate: { type: "allocator_return_press_count_at_least", count: 1 },
    effect: { type: "unlock_utility", key: "UNDO" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Uundo_unlock",
    targetLabel: "UNDO",
  },
  {
    id: "unlock_allocator_point_on_total_at_least_9",
    description: "What's the biggest number?",
    predicate: { type: "total_at_least", value: 9n },
    effect: { type: "increase_allocator_max_points", amount: 1 },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Alloc_maxPoints_plus_1_on_total_9",
    targetLabel: "λ++",
  },
  {
    id: "unlock_0_on_roll_contains_0",
    description: "Return to nothing.",
    predicate: { type: "roll_contains_value", value: 0n },
    effect: { type: "unlock_digit", key: "0" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "I0_unlock",
    targetLabel: "0",
  },
  {
    id: "unlock_minus_on_first_undo_press",
    description: "Count backwards for a bit.",
    predicate: { type: "roll_ends_with_incrementing_run", length: 7, step: -1n },
    effect: { type: "unlock_slot_operator", key: "-" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ominus_unlock",
    targetLabel: "-",
  },
  {
    id: "unlock_decrement_on_decrement_run_2",
    description: "Reverse direction.",
    predicate: { type: "roll_ends_with_incrementing_run", length: 2, step: -1n },
    effect: { type: "unlock_execution", key: "--" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ut_exec_decrement",
    targetLabel: "--",
  },
  {
    id: "unlock_4_on_total_at_least_40",
    description: "4 tens.",
    predicate: { type: "total_at_least", value: 40n },
    effect: { type: "unlock_digit", key: "4" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "I4_unlock",
    targetLabel: "4",
  },
  {
    id: "unlock_c_on_increment_run_4",
    description: "Reset and regroup.",
    predicate: { type: "allocator_allocate_press_count_at_least", count: 1 },
    effect: { type: "unlock_utility", key: "C" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Uc_unlock",
    targetLabel: "C",
  },
  {
    id: "unlock_neg_on_alt_sign_abs_run_7",
    description: "Flip every step.",
    predicate: { type: "roll_ends_with_alternating_sign_constant_abs_run", length: 7 },
    effect: { type: "unlock_digit", key: "NEG" },
    once: true,
    domainNodeId: "NZ",
    targetNodeId: "Ineg_unlock",
    targetLabel: "NEG",
  },
  {
    id: "unlock_mul_on_constant_step_gt1_run_7",
    description: "Stride in equal jumps.",
    predicate: { type: "roll_ends_with_constant_step_run", length: 7, minAbsStep: 2n },
    effect: { type: "unlock_slot_operator", key: "*" },
    once: true,
    domainNodeId: "NZ",
    targetNodeId: "Omul_unlock",
    targetLabel: "*",
  },
  {
    id: "unlock_ce_on_first_division_by_zero",
    description: "Recover from undefined.",
    predicate: { type: "division_by_zero_error_seen" },
    effect: { type: "unlock_utility", key: "CE" },
    once: true,
    domainNodeId: "NA",
    targetNodeId: "Uce_unlock_div_zero",
    targetLabel: "CE",
  },
  {
    id: "unlock_hash_on_exact_run_47_to_5_by_7",
    description: "Follow this exact trail.",
    predicate: { type: "roll_ends_with_sequence", sequence: [47n, 40n, 33n, 26n, 19n, 12n, 5n] },
    effect: { type: "unlock_slot_operator", key: "#" },
    once: true,
    domainNodeId: "NZ",
    targetNodeId: "Ohash_unlock_sequence",
    targetLabel: "#",
  },
  {
    id: "unlock_mod_on_difficult_first_euclid_equivalence",
    description: "Difficult: make # collapse to modulo.",
    predicate: { type: "operation_first_euclid_equivalent_modulo" },
    effect: { type: "unlock_slot_operator", key: "\u27E1" },
    once: true,
    difficulty: "difficult",
    domainNodeId: "NZ",
    targetNodeId: "Omod_unlock_difficult",
    targetLabel: "\u27E1",
  },
];
