import type { UnlockDefinition } from "../domain/types.js";

export const unlockCatalog: UnlockDefinition[] = [
  {
    id: "unlock_equals_on_total_11",
    description: "Make no change.",
    predicate: { type: "roll_ends_with_equal_run", length: 2 },
    effect: { type: "unlock_execution", key: "=" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ut_exec_eq",
    targetLabel: "=",
  },
  {
    id: "unlock_plus_on_equal_run_4",
    description: "Count for a bit.",
    predicate: { type: "roll_ends_with_incrementing_run", length: 7, step: 1n },
    effect: { type: "unlock_slot_operator", key: "+" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Oplus",
  },
  {
    id: "unlock_1_on_plus_press_first",
    description: "Roll over.",
    predicate: { type: "total_magnitude_at_least", value: 10n },
    effect: { type: "unlock_digit", key: "1" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "I1_unlock",
    targetLabel: "1",
  },
  {
    id: "unlock_undo_on_total_at_least_20",
    description: "Restart.",
    predicate: { type: "allocator_return_press_count_at_least", count: 1 },
    effect: { type: "unlock_utility", key: "UNDO" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Uundo_unlock",
    targetLabel: "UNDO",
  },
  {
    id: "unlock_allocator_point_on_total_at_least_9",
    description: "What's the biggest number?",
    predicate: { type: "total_at_least", value: 9n },
    effect: { type: "increase_allocator_max_points", amount: 1 },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Alloc_maxPoints_plus_1_on_total_9",
    targetLabel: "λ++",
  },
  {
    id: "unlock_0_on_roll_contains_0",
    description: "Return to nothing.",
    predicate: { type: "roll_contains_value", value: 0n },
    effect: { type: "unlock_digit", key: "0" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "I0_unlock",
    targetLabel: "0",
  },
  {
    id: "unlock_minus_on_first_undo_press",
    description: "Count backwards for a bit.",
    predicate: { type: "roll_ends_with_incrementing_run", length: 7, step: -1n },
    effect: { type: "unlock_slot_operator", key: "-" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ominus_unlock",
    targetLabel: "-",
  },
  {
    id: "unlock_decrement_on_decrement_run_2",
    description: "Reverse direction.",
    predicate: { type: "roll_ends_with_incrementing_run", length: 2, step: -1n },
    effect: { type: "unlock_execution", key: "--" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Ut_exec_decrement",
    targetLabel: "--",
  },
  {
    id: "unlock_4_on_total_at_least_40",
    description: "4 tens.",
    predicate: { type: "total_at_least", value: 40n },
    effect: { type: "unlock_digit", key: "4" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "I4_unlock",
    targetLabel: "4",
  },
  {
    id: "unlock_c_on_increment_run_4",
    description: "Reset and regroup.",
    predicate: { type: "allocator_allocate_press_count_at_least", count: 1 },
    effect: { type: "unlock_utility", key: "C" },
    once: true,
    domainNodeId: "NN",
    targetNodeId: "Uc_unlock",
    targetLabel: "C",
  },
];
